services:
  shan-tg-bot:
    image: node:24-alpine
    container_name: shan-tg-bot
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    env_file:
      - telegram-bot/.env
    restart: unless-stopped
