services:
  telegram-bot:
    image: node:24-bookworm-slim
    container_name: telegram-bot
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    env_file:
      - telegram-bot/.env
    restart: unless-stopped
